-- SQL Basic Joins

# Asian Population

SELECT SUM(POPULATION)
FROM (SELECT POPULATION, COUNTRYCODE FROM CITY) AS query1
JOIN (SELECT CONTINENT, CODE FROM COUNTRY) AS query2
ON COUNTRYCODE = CODE
WHERE CONTINENT = 'Asia'


# African Cities

SELECT NAME
FROM (SELECT NAME, COUNTRYCODE FROM CITY) AS query1
JOIN (SELECT CONTINENT, CODE FROM COUNTRY) AS query2
ON COUNTRYCODE = CODE
WHERE CONTINENT = 'Africa'

# Average Population of Each Continent

SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM COUNTRY
INNER JOIN CITY
ON COUNTRY.CODE = CITY.COUNTRYCODE
GROUP BY COUNTRY.CONTINENT

# The Report

SELECT IF (Grade < 8,NULL,Name), Grade, Marks
FROM Students
INNER JOIN Grades
ON Marks >= Min_Mark AND Marks <= Max_Mark
ORDER BY Grade DESC, Name ASC

# Ollivander's Inventory

